// Code generated by cocgen from official-swagger.yaml; DO NOT EDIT.
// 权威来源: pkg/cocapi/official-swagger.yaml
// 重新生成: go run ./cmd/warspark cocapi generate

package cocapi

import (
	"context"
	"strconv"
)

// QueryGetBuilderBaseLeagues 是 GetBuilderBaseLeagues 的查询参数。零值不传。
type QueryGetBuilderBaseLeagues struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetBuilderBaseLeagues 列出所有建筑大师联赛。支持分页。
//
// 官方端点: GET /builderbaseleagues
// 返回: BuilderBaseLeagueListResponse
func (c *Client) GetBuilderBaseLeagues(ctx context.Context, query QueryGetBuilderBaseLeagues) (BuilderBaseLeagueListResponse, error) {
	var result BuilderBaseLeagueListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/builderbaseleagues", queryMap, &result); err != nil {
		return result, err
	}
	return result, nil
}

// GetBuilderBaseLeague 获取单个建筑大师联赛信息。
//
// 官方端点: GET /builderbaseleagues/{leagueId}
// 参数: leagueId: 联赛 ID(字符串形式)
// 返回: BuilderBaseLeague
func (c *Client) GetBuilderBaseLeague(ctx context.Context, leagueId string) (BuilderBaseLeague, error) {
	var result BuilderBaseLeague
	if err := c.Get(ctx, "/builderbaseleagues/{}", &result, leagueId); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetCapitalLeagues 是 GetCapitalLeagues 的查询参数。零值不传。
type QueryGetCapitalLeagues struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetCapitalLeagues 列出所有都城联赛。支持分页。
//
// 官方端点: GET /capitalleagues
// 返回: CapitalLeagueListResponse
func (c *Client) GetCapitalLeagues(ctx context.Context, query QueryGetCapitalLeagues) (CapitalLeagueListResponse, error) {
	var result CapitalLeagueListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/capitalleagues", queryMap, &result); err != nil {
		return result, err
	}
	return result, nil
}

// GetCapitalLeague 获取单个都城联赛信息。
//
// 官方端点: GET /capitalleagues/{leagueId}
// 参数: leagueId: 联赛 ID(字符串形式)
// 返回: CapitalLeague
func (c *Client) GetCapitalLeague(ctx context.Context, leagueId string) (CapitalLeague, error) {
	var result CapitalLeague
	if err := c.Get(ctx, "/capitalleagues/{}", &result, leagueId); err != nil {
		return result, err
	}
	return result, nil
}

// QuerySearchClans 是 SearchClans 的查询参数。零值不传。
type QuerySearchClans struct {
	Name          string `json:"name,omitempty"`
	WarFrequency  string `json:"warFrequency,omitempty"`
	LocationID    int    `json:"locationId,omitempty"`
	MinMembers    int    `json:"minMembers,omitempty"`
	MaxMembers    int    `json:"maxMembers,omitempty"`
	MinClanPoints int    `json:"minClanPoints,omitempty"`
	MinClanLevel  int    `json:"minClanLevel,omitempty"`
	Limit         int    `json:"limit,omitempty"`
	After         string `json:"after,omitempty"`
	Before        string `json:"before,omitempty"`
	LabelIds      string `json:"labelIds,omitempty"`
}

// SearchClans 搜索部族。按名称和/或多种条件过滤;若用 name 至少 3 字符,至少需指定一个过滤条件。
//
// 官方端点: GET /clans
// 返回: ClanListResponse
func (c *Client) SearchClans(ctx context.Context, query QuerySearchClans) (ClanListResponse, error) {
	var result ClanListResponse
	queryMap := make(map[string]string)
	if query.Name != "" {
		queryMap["name"] = query.Name
	}
	if query.WarFrequency != "" {
		queryMap["warFrequency"] = query.WarFrequency
	}
	if query.LocationID != 0 {
		queryMap["locationId"] = strconv.Itoa(query.LocationID)
	}
	if query.MinMembers != 0 {
		queryMap["minMembers"] = strconv.Itoa(query.MinMembers)
	}
	if query.MaxMembers != 0 {
		queryMap["maxMembers"] = strconv.Itoa(query.MaxMembers)
	}
	if query.MinClanPoints != 0 {
		queryMap["minClanPoints"] = strconv.Itoa(query.MinClanPoints)
	}
	if query.MinClanLevel != 0 {
		queryMap["minClanLevel"] = strconv.Itoa(query.MinClanLevel)
	}
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if query.LabelIds != "" {
		queryMap["labelIds"] = query.LabelIds
	}
	if err := c.GetWithQuery(ctx, "/clans", queryMap, &result); err != nil {
		return result, err
	}
	return result, nil
}

// GetClan 获取部族信息。clanTag 须含 # 前缀,如 #2PP。
//
// 官方端点: GET /clans/{clanTag}
// 参数: clanTag: 部族 tag(含 #)
// 返回: Clan
func (c *Client) GetClan(ctx context.Context, clanTag string) (Clan, error) {
	var result Clan
	if err := c.Get(ctx, "/clans/{}", &result, NormalizeTag(clanTag)); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetCapitalRaidSeasons 是 GetCapitalRaidSeasons 的查询参数。零值不传。
type QueryGetCapitalRaidSeasons struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetCapitalRaidSeasons 获取部族都城突袭赛季记录。支持分页。
//
// 官方端点: GET /clans/{clanTag}/capitalraidseasons
// 参数: clanTag: 部族 tag(含 #)
// 返回: ClanCapitalRaidSeasonsResponse
func (c *Client) GetCapitalRaidSeasons(ctx context.Context, clanTag string, query QueryGetCapitalRaidSeasons) (ClanCapitalRaidSeasonsResponse, error) {
	var result ClanCapitalRaidSeasonsResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/clans/{}/capitalraidseasons", queryMap, &result, NormalizeTag(clanTag)); err != nil {
		return result, err
	}
	return result, nil
}

// GetCurrentWar 获取部族当前战争信息。含双方部族、成员、攻击详情。
//
// 官方端点: GET /clans/{clanTag}/currentwar
// 参数: clanTag: 部族 tag(含 #)
// 返回: ClanWar
func (c *Client) GetCurrentWar(ctx context.Context, clanTag string) (ClanWar, error) {
	var result ClanWar
	if err := c.Get(ctx, "/clans/{}/currentwar", &result, NormalizeTag(clanTag)); err != nil {
		return result, err
	}
	return result, nil
}

// GetClanWarLeagueGroup 获取部族当前部落战联赛(CWL)分组信息。含参赛部族和各轮次 warTag。
//
// 官方端点: GET /clans/{clanTag}/currentwar/leaguegroup
// 参数: clanTag: 部族 tag(含 #)
// 返回: ClanWarLeagueGroup
func (c *Client) GetClanWarLeagueGroup(ctx context.Context, clanTag string) (ClanWarLeagueGroup, error) {
	var result ClanWarLeagueGroup
	if err := c.Get(ctx, "/clans/{}/currentwar/leaguegroup", &result, NormalizeTag(clanTag)); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetClanMembers 是 GetClanMembers 的查询参数。零值不传。
type QueryGetClanMembers struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetClanMembers 列出部族成员。支持分页(limit/after/before)。
//
// 官方端点: GET /clans/{clanTag}/members
// 参数: clanTag: 部族 tag(含 #)
// 返回: ClanMemberListResponse
func (c *Client) GetClanMembers(ctx context.Context, clanTag string, query QueryGetClanMembers) (ClanMemberListResponse, error) {
	var result ClanMemberListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/clans/{}/members", queryMap, &result, NormalizeTag(clanTag)); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetClanWarLog 是 GetClanWarLog 的查询参数。零值不传。
type QueryGetClanWarLog struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetClanWarLog 获取部族战争日志。支持分页。
//
// 官方端点: GET /clans/{clanTag}/warlog
// 参数: clanTag: 部族 tag(含 #)
// 返回: ClanWarLogResponse
func (c *Client) GetClanWarLog(ctx context.Context, clanTag string, query QueryGetClanWarLog) (ClanWarLogResponse, error) {
	var result ClanWarLogResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/clans/{}/warlog", queryMap, &result, NormalizeTag(clanTag)); err != nil {
		return result, err
	}
	return result, nil
}

// GetClanWarLeagueWar 获取单个 CWL 战争详情。warTag 从 leaguegroup 的 rounds 中获取。
//
// 官方端点: GET /clanwarleagues/wars/{warTag}
// 参数: warTag: CWL 战争 tag(含 #)
// 返回: ClanWar
func (c *Client) GetClanWarLeagueWar(ctx context.Context, warTag string) (ClanWar, error) {
	var result ClanWar
	if err := c.Get(ctx, "/clanwarleagues/wars/{}", &result, NormalizeTag(warTag)); err != nil {
		return result, err
	}
	return result, nil
}

// GetCurrentGoldPassSeason 获取当前金币通行证赛季信息。含起止时间。
//
// 官方端点: GET /goldpass/seasons/current
// 返回: GoldPassSeason
func (c *Client) GetCurrentGoldPassSeason(ctx context.Context) (GoldPassSeason, error) {
	var result GoldPassSeason
	if err := c.Get(ctx, "/goldpass/seasons/current", &result); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetClanLabels 是 GetClanLabels 的查询参数。零值不传。
type QueryGetClanLabels struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetClanLabels 列出所有部族标签。支持分页。
//
// 官方端点: GET /labels/clans
// 返回: LabelListResponse
func (c *Client) GetClanLabels(ctx context.Context, query QueryGetClanLabels) (LabelListResponse, error) {
	var result LabelListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/labels/clans", queryMap, &result); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetPlayerLabels 是 GetPlayerLabels 的查询参数。零值不传。
type QueryGetPlayerLabels struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetPlayerLabels 列出所有玩家标签。支持分页。
//
// 官方端点: GET /labels/players
// 返回: LabelListResponse
func (c *Client) GetPlayerLabels(ctx context.Context, query QueryGetPlayerLabels) (LabelListResponse, error) {
	var result LabelListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/labels/players", queryMap, &result); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetLeagueGroup 是 GetLeagueGroup 的查询参数。零值不传。
type QueryGetLeagueGroup struct {
	PlayerTag string `json:"playerTag,omitempty"`
}

// GetLeagueGroup 获取联赛分组信息。按联赛组 tag 和赛季 ID 查询。
//
// 官方端点: GET /leaguegroup/{leagueGroupTag}/{leagueSeasonId}
// 参数: leagueGroupTag: 联赛组 tag, leagueSeasonId: 联赛赛季 ID
// 返回: LeagueGroup
func (c *Client) GetLeagueGroup(ctx context.Context, leagueGroupTag string, leagueSeasonId string, query QueryGetLeagueGroup) (LeagueGroup, error) {
	var result LeagueGroup
	queryMap := make(map[string]string)
	if query.PlayerTag != "" {
		queryMap["playerTag"] = query.PlayerTag
	}
	if err := c.GetWithQuery(ctx, "/leaguegroup/{}/{}", queryMap, &result, NormalizeTag(leagueGroupTag), leagueSeasonId); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetLeagues 是 GetLeagues 的查询参数。零值不传。
type QueryGetLeagues struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetLeagues 列出所有联赛。支持分页。
//
// 官方端点: GET /leagues
// 返回: LeagueListResponse
func (c *Client) GetLeagues(ctx context.Context, query QueryGetLeagues) (LeagueListResponse, error) {
	var result LeagueListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/leagues", queryMap, &result); err != nil {
		return result, err
	}
	return result, nil
}

// GetLeague 获取单个联赛信息。leagueId 为字符串形式的数字 ID。
//
// 官方端点: GET /leagues/{leagueId}
// 参数: leagueId: 联赛 ID(字符串形式)
// 返回: League
func (c *Client) GetLeague(ctx context.Context, leagueId string) (League, error) {
	var result League
	if err := c.Get(ctx, "/leagues/{}", &result, leagueId); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetLeagueSeasons 是 GetLeagueSeasons 的查询参数。零值不传。
type QueryGetLeagueSeasons struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetLeagueSeasons 获取联赛赛季列表。仅传奇联赛有赛季数据。
//
// 官方端点: GET /leagues/{leagueId}/seasons
// 参数: leagueId: 联赛 ID(字符串形式)
// 返回: LeagueSeasonListResponse
func (c *Client) GetLeagueSeasons(ctx context.Context, leagueId string, query QueryGetLeagueSeasons) (LeagueSeasonListResponse, error) {
	var result LeagueSeasonListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/leagues/{}/seasons", queryMap, &result, leagueId); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetLeagueSeasonRankings 是 GetLeagueSeasonRankings 的查询参数。零值不传。
type QueryGetLeagueSeasonRankings struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetLeagueSeasonRankings 获取联赛赛季排名。返回该赛季玩家排名列表。
//
// 官方端点: GET /leagues/{leagueId}/seasons/{seasonId}
// 参数: leagueId: 联赛 ID(字符串形式)
// 返回: PlayerRankingListResponse
func (c *Client) GetLeagueSeasonRankings(ctx context.Context, leagueId string, seasonId string, query QueryGetLeagueSeasonRankings) (PlayerRankingListResponse, error) {
	var result PlayerRankingListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/leagues/{}/seasons/{}", queryMap, &result, leagueId, seasonId); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetLeagueTiers 是 GetLeagueTiers 的查询参数。零值不传。
type QueryGetLeagueTiers struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetLeagueTiers 列出联赛段位。
//
// 官方端点: GET /leaguetiers
// 返回: LeagueTierListResponse
func (c *Client) GetLeagueTiers(ctx context.Context, query QueryGetLeagueTiers) (LeagueTierListResponse, error) {
	var result LeagueTierListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/leaguetiers", queryMap, &result); err != nil {
		return result, err
	}
	return result, nil
}

// GetLeagueTier 获取单个联赛段位信息。
//
// 官方端点: GET /leaguetiers/{leagueTierId}
// 参数: leagueTierId: 联赛段位 ID
// 返回: LeagueTier
func (c *Client) GetLeagueTier(ctx context.Context, leagueTierId string) (LeagueTier, error) {
	var result LeagueTier
	if err := c.Get(ctx, "/leaguetiers/{}", &result, leagueTierId); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetLocations 是 GetLocations 的查询参数。零值不传。
type QueryGetLocations struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetLocations 列出所有地区(国家/全球)。支持分页。
//
// 官方端点: GET /locations
// 返回: LocationListResponse
func (c *Client) GetLocations(ctx context.Context, query QueryGetLocations) (LocationListResponse, error) {
	var result LocationListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/locations", queryMap, &result); err != nil {
		return result, err
	}
	return result, nil
}

// GetLocation 获取单个地区信息。
//
// 官方端点: GET /locations/{locationId}
// 参数: locationId: 地区 ID(数字,全球为 32000006)
// 返回: Location
func (c *Client) GetLocation(ctx context.Context, locationId string) (Location, error) {
	var result Location
	if err := c.Get(ctx, "/locations/{}", &result, locationId); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetClanCapitalRanking 是 GetClanCapitalRanking 的查询参数。零值不传。
type QueryGetClanCapitalRanking struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetClanCapitalRanking 获取指定地区的都城排名。
//
// 官方端点: GET /locations/{locationId}/rankings/capitals
// 参数: locationId: 地区 ID(数字,全球为 32000006)
// 返回: ClanCapitalRankingListResponse
func (c *Client) GetClanCapitalRanking(ctx context.Context, locationId string, query QueryGetClanCapitalRanking) (ClanCapitalRankingListResponse, error) {
	var result ClanCapitalRankingListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/locations/{}/rankings/capitals", queryMap, &result, locationId); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetClanRanking 是 GetClanRanking 的查询参数。零值不传。
type QueryGetClanRanking struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetClanRanking 获取指定地区的部族排名。locationId 为数字,全球用 32000006。
//
// 官方端点: GET /locations/{locationId}/rankings/clans
// 参数: locationId: 地区 ID(数字,全球为 32000006)
// 返回: ClanRankingListResponse
func (c *Client) GetClanRanking(ctx context.Context, locationId string, query QueryGetClanRanking) (ClanRankingListResponse, error) {
	var result ClanRankingListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/locations/{}/rankings/clans", queryMap, &result, locationId); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetClanBuilderBaseRanking 是 GetClanBuilderBaseRanking 的查询参数。零值不传。
type QueryGetClanBuilderBaseRanking struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetClanBuilderBaseRanking 获取指定地区的建筑大师部族排名。
//
// 官方端点: GET /locations/{locationId}/rankings/clans-builder-base
// 参数: locationId: 地区 ID(数字,全球为 32000006)
// 返回: ClanBuilderBaseRankingListResponse
func (c *Client) GetClanBuilderBaseRanking(ctx context.Context, locationId string, query QueryGetClanBuilderBaseRanking) (ClanBuilderBaseRankingListResponse, error) {
	var result ClanBuilderBaseRankingListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/locations/{}/rankings/clans-builder-base", queryMap, &result, locationId); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetPlayerRanking 是 GetPlayerRanking 的查询参数。零值不传。
type QueryGetPlayerRanking struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetPlayerRanking 获取指定地区的玩家排名。
//
// 官方端点: GET /locations/{locationId}/rankings/players
// 参数: locationId: 地区 ID(数字,全球为 32000006)
// 返回: PlayerRankingListResponse
func (c *Client) GetPlayerRanking(ctx context.Context, locationId string, query QueryGetPlayerRanking) (PlayerRankingListResponse, error) {
	var result PlayerRankingListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/locations/{}/rankings/players", queryMap, &result, locationId); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetPlayerBuilderBaseRanking 是 GetPlayerBuilderBaseRanking 的查询参数。零值不传。
type QueryGetPlayerBuilderBaseRanking struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetPlayerBuilderBaseRanking 获取指定地区的建筑大师玩家排名。
//
// 官方端点: GET /locations/{locationId}/rankings/players-builder-base
// 参数: locationId: 地区 ID(数字,全球为 32000006)
// 返回: PlayerBuilderBaseRankingListResponse
func (c *Client) GetPlayerBuilderBaseRanking(ctx context.Context, locationId string, query QueryGetPlayerBuilderBaseRanking) (PlayerBuilderBaseRankingListResponse, error) {
	var result PlayerBuilderBaseRankingListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/locations/{}/rankings/players-builder-base", queryMap, &result, locationId); err != nil {
		return result, err
	}
	return result, nil
}

// GetPlayer 获取玩家信息。playerTag 须含 # 前缀,如 #2ABC。
//
// 官方端点: GET /players/{playerTag}
// 参数: playerTag: 玩家 tag(含 #)
// 返回: Player
func (c *Client) GetPlayer(ctx context.Context, playerTag string) (Player, error) {
	var result Player
	if err := c.Get(ctx, "/players/{}", &result, NormalizeTag(playerTag)); err != nil {
		return result, err
	}
	return result, nil
}

// GetBattleLog 获取玩家对战日志(1v1 攻防记录)。
//
// 官方端点: GET /players/{playerTag}/battlelog
// 参数: playerTag: 玩家 tag(含 #)
// 返回: BattleLogEntryListResponse
func (c *Client) GetBattleLog(ctx context.Context, playerTag string) (BattleLogEntryListResponse, error) {
	var result BattleLogEntryListResponse
	if err := c.Get(ctx, "/players/{}/battlelog", &result, NormalizeTag(playerTag)); err != nil {
		return result, err
	}
	return result, nil
}

// GetLeagueHistory 获取玩家联赛历史记录。
//
// 官方端点: GET /players/{playerTag}/leaguehistory
// 参数: playerTag: 玩家 tag(含 #)
// 返回: LeagueSeasonResultListResponse
func (c *Client) GetLeagueHistory(ctx context.Context, playerTag string) (LeagueSeasonResultListResponse, error) {
	var result LeagueSeasonResultListResponse
	if err := c.Get(ctx, "/players/{}/leaguehistory", &result, NormalizeTag(playerTag)); err != nil {
		return result, err
	}
	return result, nil
}

// VerifyToken 验证玩家 API token。用于校验玩家身份,token 可在游戏设置中获取,一次性使用。
//
// 官方端点: POST /players/{playerTag}/verifytoken
// 参数: playerTag: 玩家 tag(含 #)
// 请求体: VerifyTokenRequest
// 返回: VerifyTokenResponse
func (c *Client) VerifyToken(ctx context.Context, playerTag string, body VerifyTokenRequest) (VerifyTokenResponse, error) {
	var result VerifyTokenResponse
	if err := c.Post(ctx, "/players/{}/verifytoken", body, &result, NormalizeTag(playerTag)); err != nil {
		return result, err
	}
	return result, nil
}

// QueryGetWarLeagues 是 GetWarLeagues 的查询参数。零值不传。
type QueryGetWarLeagues struct {
	Limit  int    `json:"limit,omitempty"`
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// GetWarLeagues 列出所有部落战联赛。支持分页。
//
// 官方端点: GET /warleagues
// 返回: WarLeagueListResponse
func (c *Client) GetWarLeagues(ctx context.Context, query QueryGetWarLeagues) (WarLeagueListResponse, error) {
	var result WarLeagueListResponse
	queryMap := make(map[string]string)
	if query.Limit != 0 {
		queryMap["limit"] = strconv.Itoa(query.Limit)
	}
	if query.After != "" {
		queryMap["after"] = query.After
	}
	if query.Before != "" {
		queryMap["before"] = query.Before
	}
	if err := c.GetWithQuery(ctx, "/warleagues", queryMap, &result); err != nil {
		return result, err
	}
	return result, nil
}

// GetWarLeague 获取单个部落战联赛信息。
//
// 官方端点: GET /warleagues/{leagueId}
// 参数: leagueId: 联赛 ID(字符串形式)
// 返回: WarLeague
func (c *Client) GetWarLeague(ctx context.Context, leagueId string) (WarLeague, error) {
	var result WarLeague
	if err := c.Get(ctx, "/warleagues/{}", &result, leagueId); err != nil {
		return result, err
	}
	return result, nil
}
