// Code generated by scripts/generate-coc-api.go from official-swagger.yaml; DO NOT EDIT.
// 权威来源: pkg/cocapi/official-swagger.yaml (官方 Swagger 2.0 规范)
// 重新生成: go run scripts/generate-coc-api.go

package cocapi

import (
	"encoding/json"
	"fmt"
)

// Paging 列表响应的分页信息。官方规范里 list 端点响应被简化为 array,
// 但实际响应是 {items, paging},故在生成的 List struct 里统一引用本类型。
type Paging struct {
	Cursors Cursors `json:"cursors,omitempty"`
}

// Cursors 分页游标。
type Cursors struct {
	After  string `json:"after,omitempty"`
	Before string `json:"before,omitempty"`
}

// BattleLogEntry 对应官方 definition BattleLogEntry。
type BattleLogEntry struct {
	ArmyShareCode         string                `json:"armyShareCode,omitempty"`
	Attack                bool                  `json:"attack,omitempty"`
	AvailableLoot         BattleLogResourceList `json:"availableLoot,omitempty"`
	BattleTime            int                   `json:"battleTime,omitempty"`
	BattleTimestamp       string                `json:"battleTimestamp,omitempty"`
	BattleType            string                `json:"battleType,omitempty"`
	DestructionPercentage int                   `json:"destructionPercentage,omitempty"`
	ExtraLootedResources  BattleLogResourceList `json:"extraLootedResources,omitempty"`
	LootedResources       BattleLogResourceList `json:"lootedResources,omitempty"`
	OpponentName          string                `json:"opponentName,omitempty"`
	OpponentPlayerTag     string                `json:"opponentPlayerTag,omitempty"`
	OpponentTownHallLevel int                   `json:"opponentTownHallLevel,omitempty"`
	Stars                 int                   `json:"stars,omitempty"`
}

type BattleLogEntryList []BattleLogEntry

type BattleLogResourceList []Resource

// BuilderBaseLeague 对应官方 definition BuilderBaseLeague。
type BuilderBaseLeague struct {
	ID   int               `json:"id,omitempty"`
	Name JsonLocalizedName `json:"name,omitempty"`
}

type BuilderBaseLeagueList []BuilderBaseLeague

// CapitalLeague 对应官方 definition CapitalLeague。
type CapitalLeague struct {
	ID   int               `json:"id,omitempty"`
	Name JsonLocalizedName `json:"name,omitempty"`
}

type CapitalLeagueList []CapitalLeague

// Clan 对应官方 definition Clan。
type Clan struct {
	BadgeURLs                   any            `json:"badgeUrls,omitempty"`
	CapitalLeague               CapitalLeague  `json:"capitalLeague,omitempty"`
	ChatLanguage                Language       `json:"chatLanguage,omitempty"`
	ClanBuilderBasePoints       int            `json:"clanBuilderBasePoints,omitempty"`
	ClanCapital                 ClanCapital    `json:"clanCapital,omitempty"`
	ClanCapitalPoints           int            `json:"clanCapitalPoints,omitempty"`
	ClanLevel                   int            `json:"clanLevel,omitempty"`
	ClanPoints                  int            `json:"clanPoints,omitempty"`
	Description                 string         `json:"description,omitempty"`
	IsFamilyFriendly            bool           `json:"isFamilyFriendly,omitempty"`
	IsWarLogPublic              bool           `json:"isWarLogPublic,omitempty"`
	Labels                      LabelList      `json:"labels,omitempty"`
	Location                    Location       `json:"location,omitempty"`
	MemberList                  ClanMemberList `json:"memberList,omitempty"`
	Members                     int            `json:"members,omitempty"`
	Name                        string         `json:"name,omitempty"`
	RequiredBuilderBaseTrophies int            `json:"requiredBuilderBaseTrophies,omitempty"`
	RequiredLeagueTier          LeagueTier     `json:"requiredLeagueTier,omitempty"`
	RequiredTownhallLevel       int            `json:"requiredTownhallLevel,omitempty"`
	RequiredTrophies            int            `json:"requiredTrophies,omitempty"`
	Tag                         string         `json:"tag,omitempty"`
	Type                        string         `json:"type,omitempty"`
	WarFrequency                string         `json:"warFrequency,omitempty"`
	WarLeague                   WarLeague      `json:"warLeague,omitempty"`
	WarLosses                   int            `json:"warLosses,omitempty"`
	WarTies                     int            `json:"warTies,omitempty"`
	WarWinStreak                int            `json:"warWinStreak,omitempty"`
	WarWins                     int            `json:"warWins,omitempty"`
}

// ClanBuilderBaseRanking 对应官方 definition ClanBuilderBaseRanking。
type ClanBuilderBaseRanking struct {
	BadgeURLs             any      `json:"badgeUrls,omitempty"`
	ClanBuilderBasePoints int      `json:"clanBuilderBasePoints,omitempty"`
	ClanLevel             int      `json:"clanLevel,omitempty"`
	ClanPoints            int      `json:"clanPoints,omitempty"`
	Location              Location `json:"location,omitempty"`
	Members               int      `json:"members,omitempty"`
	Name                  string   `json:"name,omitempty"`
	PreviousRank          int      `json:"previousRank,omitempty"`
	Rank                  int      `json:"rank,omitempty"`
	Tag                   string   `json:"tag,omitempty"`
}

type ClanBuilderBaseRankingList []ClanBuilderBaseRanking

// ClanCapital 对应官方 definition ClanCapital。
type ClanCapital struct {
	CapitalHallLevel int                  `json:"capitalHallLevel,omitempty"`
	Districts        ClanDistrictDataList `json:"districts,omitempty"`
}

// ClanCapitalRaidSeason 对应官方 definition ClanCapitalRaidSeason。
type ClanCapitalRaidSeason struct {
	AttackLog               ClanCapitalRaidSeasonAttackLogList  `json:"attackLog,omitempty"`
	CapitalTotalLoot        int                                 `json:"capitalTotalLoot,omitempty"`
	DefenseLog              ClanCapitalRaidSeasonDefenseLogList `json:"defenseLog,omitempty"`
	DefensiveReward         int                                 `json:"defensiveReward,omitempty"`
	EndTime                 string                              `json:"endTime,omitempty"`
	EnemyDistrictsDestroyed int                                 `json:"enemyDistrictsDestroyed,omitempty"`
	Members                 ClanCapitalRaidSeasonMemberList     `json:"members,omitempty"`
	OffensiveReward         int                                 `json:"offensiveReward,omitempty"`
	RaidsCompleted          int                                 `json:"raidsCompleted,omitempty"`
	StartTime               string                              `json:"startTime,omitempty"`
	State                   string                              `json:"state,omitempty"`
	TotalAttacks            int                                 `json:"totalAttacks,omitempty"`
}

// ClanCapitalRaidSeasonAttack 对应官方 definition ClanCapitalRaidSeasonAttack。
type ClanCapitalRaidSeasonAttack struct {
	Attacker           ClanCapitalRaidSeasonAttacker `json:"attacker,omitempty"`
	DestructionPercent int                           `json:"destructionPercent,omitempty"`
	Stars              int                           `json:"stars,omitempty"`
}

type ClanCapitalRaidSeasonAttackList []ClanCapitalRaidSeasonAttack

// ClanCapitalRaidSeasonAttackLogEntry 对应官方 definition ClanCapitalRaidSeasonAttackLogEntry。
type ClanCapitalRaidSeasonAttackLogEntry struct {
	AttackCount        int                               `json:"attackCount,omitempty"`
	Defender           ClanCapitalRaidSeasonClanInfo     `json:"defender,omitempty"`
	DistrictCount      int                               `json:"districtCount,omitempty"`
	Districts          ClanCapitalRaidSeasonDistrictList `json:"districts,omitempty"`
	DistrictsDestroyed int                               `json:"districtsDestroyed,omitempty"`
}

type ClanCapitalRaidSeasonAttackLogList []ClanCapitalRaidSeasonAttackLogEntry

// ClanCapitalRaidSeasonAttacker 对应官方 definition ClanCapitalRaidSeasonAttacker。
type ClanCapitalRaidSeasonAttacker struct {
	Name string `json:"name,omitempty"`
	Tag  string `json:"tag,omitempty"`
}

// ClanCapitalRaidSeasonClanInfo 对应官方 definition ClanCapitalRaidSeasonClanInfo。
type ClanCapitalRaidSeasonClanInfo struct {
	BadgeURLs any    `json:"badgeUrls,omitempty"`
	Level     int    `json:"level,omitempty"`
	Name      string `json:"name,omitempty"`
	Tag       string `json:"tag,omitempty"`
}

// ClanCapitalRaidSeasonDefenseLogEntry 对应官方 definition ClanCapitalRaidSeasonDefenseLogEntry。
type ClanCapitalRaidSeasonDefenseLogEntry struct {
	AttackCount        int                               `json:"attackCount,omitempty"`
	Attacker           ClanCapitalRaidSeasonClanInfo     `json:"attacker,omitempty"`
	DistrictCount      int                               `json:"districtCount,omitempty"`
	Districts          ClanCapitalRaidSeasonDistrictList `json:"districts,omitempty"`
	DistrictsDestroyed int                               `json:"districtsDestroyed,omitempty"`
}

type ClanCapitalRaidSeasonDefenseLogList []ClanCapitalRaidSeasonDefenseLogEntry

// ClanCapitalRaidSeasonDistrict 对应官方 definition ClanCapitalRaidSeasonDistrict。
type ClanCapitalRaidSeasonDistrict struct {
	AttackCount        int                             `json:"attackCount,omitempty"`
	Attacks            ClanCapitalRaidSeasonAttackList `json:"attacks,omitempty"`
	DestructionPercent int                             `json:"destructionPercent,omitempty"`
	DistrictHallLevel  int                             `json:"districtHallLevel,omitempty"`
	ID                 int                             `json:"id,omitempty"`
	Name               JsonLocalizedName               `json:"name,omitempty"`
	Stars              int                             `json:"stars,omitempty"`
	TotalLooted        int                             `json:"totalLooted,omitempty"`
}

type ClanCapitalRaidSeasonDistrictList []ClanCapitalRaidSeasonDistrict

// ClanCapitalRaidSeasonMember 对应官方 definition ClanCapitalRaidSeasonMember。
type ClanCapitalRaidSeasonMember struct {
	AttackLimit            int    `json:"attackLimit,omitempty"`
	Attacks                int    `json:"attacks,omitempty"`
	BonusAttackLimit       int    `json:"bonusAttackLimit,omitempty"`
	CapitalResourcesLooted int    `json:"capitalResourcesLooted,omitempty"`
	Name                   string `json:"name,omitempty"`
	Tag                    string `json:"tag,omitempty"`
}

type ClanCapitalRaidSeasonMemberList []ClanCapitalRaidSeasonMember

type ClanCapitalRaidSeasons []ClanCapitalRaidSeason

// ClanCapitalRanking 对应官方 definition ClanCapitalRanking。
type ClanCapitalRanking struct {
	BadgeURLs         any      `json:"badgeUrls,omitempty"`
	ClanCapitalPoints int      `json:"clanCapitalPoints,omitempty"`
	ClanLevel         int      `json:"clanLevel,omitempty"`
	ClanPoints        int      `json:"clanPoints,omitempty"`
	Location          Location `json:"location,omitempty"`
	Members           int      `json:"members,omitempty"`
	Name              string   `json:"name,omitempty"`
	PreviousRank      int      `json:"previousRank,omitempty"`
	Rank              int      `json:"rank,omitempty"`
	Tag               string   `json:"tag,omitempty"`
}

type ClanCapitalRankingList []ClanCapitalRanking

// ClanDistrictData 对应官方 definition ClanDistrictData。
type ClanDistrictData struct {
	DistrictHallLevel int               `json:"districtHallLevel,omitempty"`
	ID                int               `json:"id,omitempty"`
	Name              JsonLocalizedName `json:"name,omitempty"`
}

type ClanDistrictDataList []ClanDistrictData

type ClanList []Clan

// ClanMember 对应官方 definition ClanMember。
type ClanMember struct {
	BuilderBaseLeague   BuilderBaseLeague `json:"builderBaseLeague,omitempty"`
	BuilderBaseTrophies int               `json:"builderBaseTrophies,omitempty"`
	ClanRank            int               `json:"clanRank,omitempty"`
	Donations           int               `json:"donations,omitempty"`
	DonationsReceived   int               `json:"donationsReceived,omitempty"`
	ExpLevel            int               `json:"expLevel,omitempty"`
	League              League            `json:"league,omitempty"`
	LeagueTier          LeagueTier        `json:"leagueTier,omitempty"`
	Name                string            `json:"name,omitempty"`
	PlayerHouse         PlayerHouse       `json:"playerHouse,omitempty"`
	PreviousClanRank    int               `json:"previousClanRank,omitempty"`
	Role                string            `json:"role,omitempty"`
	Tag                 string            `json:"tag,omitempty"`
	TownHallLevel       int               `json:"townHallLevel,omitempty"`
	Trophies            int               `json:"trophies,omitempty"`
}

type ClanMemberList []ClanMember

// ClanRanking 对应官方 definition ClanRanking。
type ClanRanking struct {
	BadgeURLs    any      `json:"badgeUrls,omitempty"`
	ClanLevel    int      `json:"clanLevel,omitempty"`
	ClanPoints   int      `json:"clanPoints,omitempty"`
	Location     Location `json:"location,omitempty"`
	Members      int      `json:"members,omitempty"`
	Name         string   `json:"name,omitempty"`
	PreviousRank int      `json:"previousRank,omitempty"`
	Rank         int      `json:"rank,omitempty"`
	Tag          string   `json:"tag,omitempty"`
}

type ClanRankingList []ClanRanking

// ClanWar 对应官方 definition ClanWar。
type ClanWar struct {
	AttacksPerMember     int     `json:"attacksPerMember,omitempty"`
	BattleModifier       string  `json:"battleModifier,omitempty"`
	Clan                 WarClan `json:"clan,omitempty"`
	EndTime              string  `json:"endTime,omitempty"`
	Opponent             WarClan `json:"opponent,omitempty"`
	PreparationStartTime string  `json:"preparationStartTime,omitempty"`
	StartTime            string  `json:"startTime,omitempty"`
	State                string  `json:"state,omitempty"`
	TeamSize             int     `json:"teamSize,omitempty"`
}

// ClanWarAttack 对应官方 definition ClanWarAttack。
type ClanWarAttack struct {
	AttackerTag           string `json:"attackerTag,omitempty"`
	DefenderTag           string `json:"defenderTag,omitempty"`
	DestructionPercentage int    `json:"destructionPercentage,omitempty"`
	Duration              int    `json:"duration,omitempty"`
	Order                 int    `json:"order,omitempty"`
	Stars                 int    `json:"stars,omitempty"`
}

type ClanWarAttackList []ClanWarAttack

// ClanWarLeagueClan 对应官方 definition ClanWarLeagueClan。
type ClanWarLeagueClan struct {
	BadgeURLs any                         `json:"badgeUrls,omitempty"`
	ClanLevel int                         `json:"clanLevel,omitempty"`
	Members   ClanWarLeagueClanMemberList `json:"members,omitempty"`
	Name      string                      `json:"name,omitempty"`
	Tag       string                      `json:"tag,omitempty"`
}

type ClanWarLeagueClanList []ClanWarLeagueClan

// ClanWarLeagueClanMember 对应官方 definition ClanWarLeagueClanMember。
type ClanWarLeagueClanMember struct {
	Name          string `json:"name,omitempty"`
	Tag           string `json:"tag,omitempty"`
	TownHallLevel int    `json:"townHallLevel,omitempty"`
}

type ClanWarLeagueClanMemberList []ClanWarLeagueClanMember

// ClanWarLeagueGroup 对应官方 definition ClanWarLeagueGroup。
type ClanWarLeagueGroup struct {
	Clans  ClanWarLeagueClanList  `json:"clans,omitempty"`
	Rounds ClanWarLeagueRoundList `json:"rounds,omitempty"`
	Season string                 `json:"season,omitempty"`
	State  string                 `json:"state,omitempty"`
	Tag    string                 `json:"tag,omitempty"`
}

// ClanWarLeagueRound 对应官方 definition ClanWarLeagueRound。
type ClanWarLeagueRound struct {
	WarTags StringList `json:"warTags,omitempty"`
}

type ClanWarLeagueRoundList []ClanWarLeagueRound

type ClanWarLog []ClanWarLogEntry

// ClanWarLogEntry 对应官方 definition ClanWarLogEntry。
type ClanWarLogEntry struct {
	AttacksPerMember int     `json:"attacksPerMember,omitempty"`
	BattleModifier   string  `json:"battleModifier,omitempty"`
	Clan             WarClan `json:"clan,omitempty"`
	EndTime          string  `json:"endTime,omitempty"`
	Opponent         WarClan `json:"opponent,omitempty"`
	Result           string  `json:"result,omitempty"`
	TeamSize         int     `json:"teamSize,omitempty"`
}

// ClanWarMember 对应官方 definition ClanWarMember。
type ClanWarMember struct {
	Attacks            ClanWarAttackList `json:"attacks,omitempty"`
	BestOpponentAttack ClanWarAttack     `json:"bestOpponentAttack,omitempty"`
	MapPosition        int               `json:"mapPosition,omitempty"`
	Name               string            `json:"name,omitempty"`
	OpponentAttacks    int               `json:"opponentAttacks,omitempty"`
	Tag                string            `json:"tag,omitempty"`
	TownhallLevel      int               `json:"townhallLevel,omitempty"`
}

type ClanWarMemberList []ClanWarMember

// ClientError 对应官方 definition ClientError。
type ClientError struct {
	Detail  any    `json:"detail,omitempty"`
	Message string `json:"message,omitempty"`
	Reason  string `json:"reason,omitempty"`
	Type    string `json:"type,omitempty"`
}

// DeepLinkCreationRequest 对应官方 definition DeepLinkCreationRequest。
type DeepLinkCreationRequest struct {
	ClanTag         string     `json:"clanTag,omitempty"`
	OpponentClanTag string     `json:"opponentClanTag,omitempty"`
	PlayerTags      StringList `json:"playerTags,omitempty"`
}

// DeepLinkCreationResponse 对应官方 definition DeepLinkCreationResponse。
type DeepLinkCreationResponse struct {
	Link string `json:"link,omitempty"`
}

// Float 官方规范未定义具体字段,按动态对象处理。
type Float map[string]any

// GoldPassSeason 对应官方 definition GoldPassSeason。
type GoldPassSeason struct {
	EndTime   string `json:"endTime,omitempty"`
	StartTime string `json:"startTime,omitempty"`
}

// JsonLocalizedName 官方规范定义不完整,基于实际 API 调用验证做特殊处理。
type JsonLocalizedName string

// UnmarshalJSON 兼容官方规范(object)与实际响应(string)。
func (j *JsonLocalizedName) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		*j = JsonLocalizedName(s)
		return nil
	}
	// object 形式:取 en 字段或首个字符串值
	var m map[string]any
	if err := json.Unmarshal(data, &m); err == nil {
		if v, ok := m["en"].(string); ok {
			*j = JsonLocalizedName(v)
			return nil
		}
		for _, v := range m {
			if s, ok := v.(string); ok {
				*j = JsonLocalizedName(s)
				return nil
			}
		}
	}
	*j = ""
	return nil
}

// JsonNode 官方规范未定义具体字段,按动态对象处理。
type JsonNode map[string]any

// Label 对应官方 definition Label。
type Label struct {
	IconURLs any               `json:"iconUrls,omitempty"`
	ID       int               `json:"id,omitempty"`
	Name     JsonLocalizedName `json:"name,omitempty"`
}

type LabelList []Label

// Language 对应官方 definition Language。
type Language struct {
	ID           int    `json:"id,omitempty"`
	LanguageCode string `json:"languageCode,omitempty"`
	Name         string `json:"name,omitempty"`
}

// League 对应官方 definition League。
type League struct {
	IconURLs any               `json:"iconUrls,omitempty"`
	ID       int               `json:"id,omitempty"`
	Name     JsonLocalizedName `json:"name,omitempty"`
}

// LeagueBattleLogEntry 对应官方 definition LeagueBattleLogEntry。
type LeagueBattleLogEntry struct {
	CreationTime          string `json:"creationTime,omitempty"`
	DestructionPercentage int    `json:"destructionPercentage,omitempty"`
	OpponentName          string `json:"opponentName,omitempty"`
	OpponentPlayerTag     string `json:"opponentPlayerTag,omitempty"`
	Stars                 int    `json:"stars,omitempty"`
	Trophies              int    `json:"trophies,omitempty"`
}

// LeagueGroup 对应官方 definition LeagueGroup。
type LeagueGroup struct {
	AttackLogs  LeagueGroupBattleLogEntryList `json:"attackLogs,omitempty"`
	DefenseLogs LeagueGroupBattleLogEntryList `json:"defenseLogs,omitempty"`
	Members     LeagueGroupMemberList         `json:"members,omitempty"`
}

type LeagueGroupBattleLogEntryList []LeagueBattleLogEntry

// LeagueGroupMember 对应官方 definition LeagueGroupMember。
type LeagueGroupMember struct {
	AttackLoseCount  int    `json:"attackLoseCount,omitempty"`
	AttackWinCount   int    `json:"attackWinCount,omitempty"`
	ClanName         string `json:"clanName,omitempty"`
	ClanTag          string `json:"clanTag,omitempty"`
	DefenseLoseCount int    `json:"defenseLoseCount,omitempty"`
	DefenseWinCount  int    `json:"defenseWinCount,omitempty"`
	LeagueTrophies   int    `json:"leagueTrophies,omitempty"`
	PlayerName       string `json:"playerName,omitempty"`
	PlayerTag        string `json:"playerTag,omitempty"`
}

type LeagueGroupMemberList []LeagueGroupMember

type LeagueList []League

// LeagueSeason 对应官方 definition LeagueSeason。
type LeagueSeason struct {
	ID string `json:"id,omitempty"`
}

type LeagueSeasonList []LeagueSeason

// LeagueSeasonResult 对应官方 definition LeagueSeasonResult。
type LeagueSeasonResult struct {
	AttackLosses   int  `json:"attackLosses,omitempty"`
	AttackStars    int  `json:"attackStars,omitempty"`
	AttackWins     int  `json:"attackWins,omitempty"`
	DefenseLosses  int  `json:"defenseLosses,omitempty"`
	DefenseStars   int  `json:"defenseStars,omitempty"`
	DefenseWins    int  `json:"defenseWins,omitempty"`
	LeagueSeasonID long `json:"leagueSeasonId,omitempty"`
	LeagueTierID   int  `json:"leagueTierId,omitempty"`
	LeagueTrophies int  `json:"leagueTrophies,omitempty"`
	MaxBattles     int  `json:"maxBattles,omitempty"`
	Placement      int  `json:"placement,omitempty"`
}

type LeagueSeasonResultList []LeagueSeasonResult

// LeagueTier 对应官方 definition LeagueTier。
type LeagueTier struct {
	IconURLs any               `json:"iconUrls,omitempty"`
	ID       int               `json:"id,omitempty"`
	Name     JsonLocalizedName `json:"name,omitempty"`
}

type LeagueTierList []LeagueTier

// LegendLeagueTournamentSeasonResult 对应官方 definition LegendLeagueTournamentSeasonResult。
type LegendLeagueTournamentSeasonResult struct {
	ID       string `json:"id,omitempty"`
	Rank     int    `json:"rank,omitempty"`
	Trophies int    `json:"trophies,omitempty"`
}

// Location 对应官方 definition Location。
type Location struct {
	CountryCode   string `json:"countryCode,omitempty"`
	ID            int    `json:"id,omitempty"`
	IsCountry     bool   `json:"isCountry,omitempty"`
	LocalizedName string `json:"localizedName,omitempty"`
	Name          string `json:"name,omitempty"`
}

type LocationList []Location

// Long 官方规范定义不完整,基于实际 API 调用验证做特殊处理。
type Long int64

// UnmarshalJSON 兼容数字和字符串形式的数字。
func (l *Long) UnmarshalJSON(data []byte) error {
	var n int64
	if err := json.Unmarshal(data, &n); err == nil {
		*l = Long(n)
		return nil
	}
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		var n int64
		if _, err := fmt.Sscanf(s, "%d", &n); err == nil {
			*l = Long(n)
			return nil
		}
	}
	*l = 0
	return nil
}

// Player 对应官方 definition Player。
type Player struct {
	Achievements             PlayerAchievementProgressList `json:"achievements,omitempty"`
	AttackWins               int                           `json:"attackWins,omitempty"`
	BestBuilderBaseTrophies  int                           `json:"bestBuilderBaseTrophies,omitempty"`
	BestTrophies             int                           `json:"bestTrophies,omitempty"`
	BuilderBaseLeague        BuilderBaseLeague             `json:"builderBaseLeague,omitempty"`
	BuilderBaseTrophies      int                           `json:"builderBaseTrophies,omitempty"`
	BuilderHallLevel         int                           `json:"builderHallLevel,omitempty"`
	Clan                     PlayerClan                    `json:"clan,omitempty"`
	ClanCapitalContributions int                           `json:"clanCapitalContributions,omitempty"`
	CurrentLeagueGroupTag    string                        `json:"currentLeagueGroupTag,omitempty"`
	CurrentLeagueSeasonID    Long                          `json:"currentLeagueSeasonId,omitempty"`
	DefenseWins              int                           `json:"defenseWins,omitempty"`
	Donations                int                           `json:"donations,omitempty"`
	DonationsReceived        int                           `json:"donationsReceived,omitempty"`
	ExpLevel                 int                           `json:"expLevel,omitempty"`
	HeroEquipment            PlayerItemLevelList           `json:"heroEquipment,omitempty"`
	Heroes                   PlayerItemLevelList           `json:"heroes,omitempty"`
	Labels                   LabelList                     `json:"labels,omitempty"`
	League                   League                        `json:"league,omitempty"`
	LeagueTier               LeagueTier                    `json:"leagueTier,omitempty"`
	LegendStatistics         PlayerLegendStatistics        `json:"legendStatistics,omitempty"`
	Name                     string                        `json:"name,omitempty"`
	PlayerHouse              PlayerHouse                   `json:"playerHouse,omitempty"`
	PreviousLeagueGroupTag   string                        `json:"previousLeagueGroupTag,omitempty"`
	PreviousLeagueSeasonID   Long                          `json:"previousLeagueSeasonId,omitempty"`
	Role                     string                        `json:"role,omitempty"`
	Spells                   PlayerItemLevelList           `json:"spells,omitempty"`
	Tag                      string                        `json:"tag,omitempty"`
	TownHallLevel            int                           `json:"townHallLevel,omitempty"`
	TownHallWeaponLevel      int                           `json:"townHallWeaponLevel,omitempty"`
	Troops                   PlayerItemLevelList           `json:"troops,omitempty"`
	Trophies                 int                           `json:"trophies,omitempty"`
	WarPreference            string                        `json:"warPreference,omitempty"`
	WarStars                 int                           `json:"warStars,omitempty"`
}

// PlayerAchievementProgress 对应官方 definition PlayerAchievementProgress。
type PlayerAchievementProgress struct {
	CompletionInfo JsonLocalizedName `json:"completionInfo,omitempty"`
	Info           JsonLocalizedName `json:"info,omitempty"`
	Name           JsonLocalizedName `json:"name,omitempty"`
	Stars          int               `json:"stars,omitempty"`
	Target         int               `json:"target,omitempty"`
	Value          int               `json:"value,omitempty"`
	Village        string            `json:"village,omitempty"`
}

type PlayerAchievementProgressList []PlayerAchievementProgress

// PlayerBuilderBaseRanking 对应官方 definition PlayerBuilderBaseRanking。
type PlayerBuilderBaseRanking struct {
	BuilderBaseLeague   BuilderBaseLeague `json:"builderBaseLeague,omitempty"`
	BuilderBaseTrophies int               `json:"builderBaseTrophies,omitempty"`
	Clan                PlayerRankingClan `json:"clan,omitempty"`
	ExpLevel            int               `json:"expLevel,omitempty"`
	Name                string            `json:"name,omitempty"`
	PreviousRank        int               `json:"previousRank,omitempty"`
	Rank                int               `json:"rank,omitempty"`
	Tag                 string            `json:"tag,omitempty"`
}

type PlayerBuilderBaseRankingList []PlayerBuilderBaseRanking

// PlayerClan 对应官方 definition PlayerClan。
type PlayerClan struct {
	BadgeURLs any    `json:"badgeUrls,omitempty"`
	ClanLevel int    `json:"clanLevel,omitempty"`
	Name      string `json:"name,omitempty"`
	Tag       string `json:"tag,omitempty"`
}

// PlayerHouse 对应官方 definition PlayerHouse。
type PlayerHouse struct {
	Elements PlayerHouseElementList `json:"elements,omitempty"`
}

// PlayerHouseElement 对应官方 definition PlayerHouseElement。
type PlayerHouseElement struct {
	ID   int    `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}

type PlayerHouseElementList []PlayerHouseElement

// PlayerItemLevel 对应官方 definition PlayerItemLevel。
type PlayerItemLevel struct {
	Equipment          PlayerItemLevelList `json:"equipment,omitempty"`
	Level              int                 `json:"level,omitempty"`
	MaxLevel           int                 `json:"maxLevel,omitempty"`
	Name               JsonLocalizedName   `json:"name,omitempty"`
	SuperTroopIsActive bool                `json:"superTroopIsActive,omitempty"`
	Village            string              `json:"village,omitempty"`
}

type PlayerItemLevelList []PlayerItemLevel

// PlayerLegendStatistics 对应官方 definition PlayerLegendStatistics。
type PlayerLegendStatistics struct {
	BestBuilderBaseSeason     LegendLeagueTournamentSeasonResult `json:"bestBuilderBaseSeason,omitempty"`
	BestSeason                LegendLeagueTournamentSeasonResult `json:"bestSeason,omitempty"`
	CurrentSeason             LegendLeagueTournamentSeasonResult `json:"currentSeason,omitempty"`
	LegendTrophies            int                                `json:"legendTrophies,omitempty"`
	PreviousBuilderBaseSeason LegendLeagueTournamentSeasonResult `json:"previousBuilderBaseSeason,omitempty"`
	PreviousSeason            LegendLeagueTournamentSeasonResult `json:"previousSeason,omitempty"`
}

// PlayerRanking 对应官方 definition PlayerRanking。
type PlayerRanking struct {
	AttackWins   int               `json:"attackWins,omitempty"`
	Clan         PlayerRankingClan `json:"clan,omitempty"`
	DefenseWins  int               `json:"defenseWins,omitempty"`
	ExpLevel     int               `json:"expLevel,omitempty"`
	League       League            `json:"league,omitempty"`
	LeagueTier   LeagueTier        `json:"leagueTier,omitempty"`
	Name         string            `json:"name,omitempty"`
	PreviousRank int               `json:"previousRank,omitempty"`
	Rank         int               `json:"rank,omitempty"`
	Tag          string            `json:"tag,omitempty"`
	Trophies     int               `json:"trophies,omitempty"`
}

// PlayerRankingClan 对应官方 definition PlayerRankingClan。
type PlayerRankingClan struct {
	BadgeURLs any    `json:"badgeUrls,omitempty"`
	Name      string `json:"name,omitempty"`
	Tag       string `json:"tag,omitempty"`
}

type PlayerRankingList []PlayerRanking

// PlayerVillage 对应官方 definition PlayerVillage。
type PlayerVillage struct {
	Tag     string   `json:"tag,omitempty"`
	Village JsonNode `json:"village,omitempty"`
}

// Replay 对应官方 definition Replay。
type Replay struct {
	ReplayData JsonNode `json:"replayData,omitempty"`
	ReplayTag  string   `json:"replayTag,omitempty"`
}

// Resource 对应官方 definition Resource。
type Resource struct {
	Amount long   `json:"amount,omitempty"`
	Name   string `json:"name,omitempty"`
}

// ServiceVersion 对应官方 definition ServiceVersion。
type ServiceVersion struct {
	Content int `json:"content,omitempty"`
	Major   int `json:"major,omitempty"`
	Minor   int `json:"minor,omitempty"`
}

// String 官方规范未定义具体字段,按动态对象处理。
type String map[string]any

type StringList []string

// VerifyTokenRequest 对应官方 definition VerifyTokenRequest。
type VerifyTokenRequest struct {
	Token string `json:"token,omitempty"`
}

// VerifyTokenResponse 对应官方 definition VerifyTokenResponse。
type VerifyTokenResponse struct {
	Status string `json:"status,omitempty"`
	Tag    string `json:"tag,omitempty"`
	Token  string `json:"token,omitempty"`
}

// WarClan 对应官方 definition WarClan。
type WarClan struct {
	Attacks               int               `json:"attacks,omitempty"`
	BadgeURLs             any               `json:"badgeUrls,omitempty"`
	ClanLevel             int               `json:"clanLevel,omitempty"`
	DestructionPercentage Float             `json:"destructionPercentage,omitempty"`
	ExpEarned             int               `json:"expEarned,omitempty"`
	Members               ClanWarMemberList `json:"members,omitempty"`
	Name                  string            `json:"name,omitempty"`
	Stars                 int               `json:"stars,omitempty"`
	Tag                   string            `json:"tag,omitempty"`
}

// WarLeague 对应官方 definition WarLeague。
type WarLeague struct {
	ID   int               `json:"id,omitempty"`
	Name JsonLocalizedName `json:"name,omitempty"`
}

type WarLeagueList []WarLeague

// WarStatus 对应官方 definition WarStatus。
type WarStatus struct {
	ClanTag      string `json:"clanTag,omitempty"`
	EnemyClanTag string `json:"enemyClanTag,omitempty"`
	StatusCode   int    `json:"statusCode,omitempty"`
	Timestamp    string `json:"timestamp,omitempty"`
	WarState     string `json:"warState,omitempty"`
}

type WarStatusList []WarStatus

// long 官方规范未定义具体字段,按动态对象处理。
type long map[string]any

// LocationListResponse 是 LocationList 端点响应的包装(带分页)。
// 官方规范把 LocationList 定义为 array,但实际响应是 {items, paging} 对象。
type LocationListResponse struct {
	Items  []Location `json:"items,omitempty"`
	Paging Paging     `json:"paging,omitempty"`
}

// LabelListResponse 是 LabelList 端点响应的包装(带分页)。
// 官方规范把 LabelList 定义为 array,但实际响应是 {items, paging} 对象。
type LabelListResponse struct {
	Items  []Label `json:"items,omitempty"`
	Paging Paging  `json:"paging,omitempty"`
}

// LeagueListResponse 是 LeagueList 端点响应的包装(带分页)。
// 官方规范把 LeagueList 定义为 array,但实际响应是 {items, paging} 对象。
type LeagueListResponse struct {
	Items  []League `json:"items,omitempty"`
	Paging Paging   `json:"paging,omitempty"`
}

// LeagueSeasonListResponse 是 LeagueSeasonList 端点响应的包装(带分页)。
// 官方规范把 LeagueSeasonList 定义为 array,但实际响应是 {items, paging} 对象。
type LeagueSeasonListResponse struct {
	Items  []LeagueSeason `json:"items,omitempty"`
	Paging Paging         `json:"paging,omitempty"`
}

// ClanCapitalRankingListResponse 是 ClanCapitalRankingList 端点响应的包装(带分页)。
// 官方规范把 ClanCapitalRankingList 定义为 array,但实际响应是 {items, paging} 对象。
type ClanCapitalRankingListResponse struct {
	Items  []ClanCapitalRanking `json:"items,omitempty"`
	Paging Paging               `json:"paging,omitempty"`
}

// BattleLogEntryListResponse 是 BattleLogEntryList 端点响应的包装(带分页)。
// 官方规范把 BattleLogEntryList 定义为 array,但实际响应是 {items, paging} 对象。
type BattleLogEntryListResponse struct {
	Items  []BattleLogEntry `json:"items,omitempty"`
	Paging Paging           `json:"paging,omitempty"`
}

// LeagueSeasonResultListResponse 是 LeagueSeasonResultList 端点响应的包装(带分页)。
// 官方规范把 LeagueSeasonResultList 定义为 array,但实际响应是 {items, paging} 对象。
type LeagueSeasonResultListResponse struct {
	Items  []LeagueSeasonResult `json:"items,omitempty"`
	Paging Paging               `json:"paging,omitempty"`
}

// ClanCapitalRaidSeasonsResponse 是 ClanCapitalRaidSeasons 端点响应的包装(带分页)。
// 官方规范把 ClanCapitalRaidSeasons 定义为 array,但实际响应是 {items, paging} 对象。
type ClanCapitalRaidSeasonsResponse struct {
	Items  []ClanCapitalRaidSeason `json:"items,omitempty"`
	Paging Paging                  `json:"paging,omitempty"`
}

// ClanBuilderBaseRankingListResponse 是 ClanBuilderBaseRankingList 端点响应的包装(带分页)。
// 官方规范把 ClanBuilderBaseRankingList 定义为 array,但实际响应是 {items, paging} 对象。
type ClanBuilderBaseRankingListResponse struct {
	Items  []ClanBuilderBaseRanking `json:"items,omitempty"`
	Paging Paging                   `json:"paging,omitempty"`
}

// PlayerBuilderBaseRankingListResponse 是 PlayerBuilderBaseRankingList 端点响应的包装(带分页)。
// 官方规范把 PlayerBuilderBaseRankingList 定义为 array,但实际响应是 {items, paging} 对象。
type PlayerBuilderBaseRankingListResponse struct {
	Items  []PlayerBuilderBaseRanking `json:"items,omitempty"`
	Paging Paging                     `json:"paging,omitempty"`
}

// WarLeagueListResponse 是 WarLeagueList 端点响应的包装(带分页)。
// 官方规范把 WarLeagueList 定义为 array,但实际响应是 {items, paging} 对象。
type WarLeagueListResponse struct {
	Items  []WarLeague `json:"items,omitempty"`
	Paging Paging      `json:"paging,omitempty"`
}

// CapitalLeagueListResponse 是 CapitalLeagueList 端点响应的包装(带分页)。
// 官方规范把 CapitalLeagueList 定义为 array,但实际响应是 {items, paging} 对象。
type CapitalLeagueListResponse struct {
	Items  []CapitalLeague `json:"items,omitempty"`
	Paging Paging          `json:"paging,omitempty"`
}

// LeagueTierListResponse 是 LeagueTierList 端点响应的包装(带分页)。
// 官方规范把 LeagueTierList 定义为 array,但实际响应是 {items, paging} 对象。
type LeagueTierListResponse struct {
	Items  []LeagueTier `json:"items,omitempty"`
	Paging Paging       `json:"paging,omitempty"`
}

// ClanRankingListResponse 是 ClanRankingList 端点响应的包装(带分页)。
// 官方规范把 ClanRankingList 定义为 array,但实际响应是 {items, paging} 对象。
type ClanRankingListResponse struct {
	Items  []ClanRanking `json:"items,omitempty"`
	Paging Paging        `json:"paging,omitempty"`
}

// BuilderBaseLeagueListResponse 是 BuilderBaseLeagueList 端点响应的包装(带分页)。
// 官方规范把 BuilderBaseLeagueList 定义为 array,但实际响应是 {items, paging} 对象。
type BuilderBaseLeagueListResponse struct {
	Items  []BuilderBaseLeague `json:"items,omitempty"`
	Paging Paging              `json:"paging,omitempty"`
}

// ClanListResponse 是 ClanList 端点响应的包装(带分页)。
// 官方规范把 ClanList 定义为 array,但实际响应是 {items, paging} 对象。
type ClanListResponse struct {
	Items  []Clan `json:"items,omitempty"`
	Paging Paging `json:"paging,omitempty"`
}

// ClanMemberListResponse 是 ClanMemberList 端点响应的包装(带分页)。
// 官方规范把 ClanMemberList 定义为 array,但实际响应是 {items, paging} 对象。
type ClanMemberListResponse struct {
	Items  []ClanMember `json:"items,omitempty"`
	Paging Paging       `json:"paging,omitempty"`
}

// ClanWarLogResponse 是 ClanWarLog 端点响应的包装(带分页)。
// 官方规范把 ClanWarLog 定义为 array,但实际响应是 {items, paging} 对象。
type ClanWarLogResponse struct {
	Items  []ClanWarLogEntry `json:"items,omitempty"`
	Paging Paging            `json:"paging,omitempty"`
}

// PlayerRankingListResponse 是 PlayerRankingList 端点响应的包装(带分页)。
// 官方规范把 PlayerRankingList 定义为 array,但实际响应是 {items, paging} 对象。
type PlayerRankingListResponse struct {
	Items  []PlayerRanking `json:"items,omitempty"`
	Paging Paging          `json:"paging,omitempty"`
}
