// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/audit-logs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-layouts"
                ],
                "summary": "List admin audit logs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/layout-links/{link_id}": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-layouts"
                ],
                "summary": "Update layout link",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/layouts": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-layouts"
                ],
                "summary": "Create layout draft",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/layouts/{layout_id}/links": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-layouts"
                ],
                "summary": "Add layout link",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/layouts/{layout_id}/video-matches": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-layouts"
                ],
                "summary": "Add layout video match",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/review-queue": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-layouts"
                ],
                "summary": "List review queue",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/review/{resource_type}/{resource_id}": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-layouts"
                ],
                "summary": "Update review status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/builder-base-leagues": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capital"
                ],
                "summary": "获取夜世界联赛列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/builder-base-leagues/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capital"
                ],
                "summary": "获取夜世界联赛详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "联赛ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/capital-leagues": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capital"
                ],
                "summary": "获取都城联赛列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/capital-leagues/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capital"
                ],
                "summary": "获取都城联赛详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "联赛ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/clans": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utility"
                ],
                "summary": "搜索部落",
                "parameters": [
                    {
                        "type": "string",
                        "description": "部落名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "战争频率",
                        "name": "warFrequency",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "位置ID",
                        "name": "locationId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最少成员数",
                        "name": "minMembers",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最多成员数",
                        "name": "maxMembers",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最少部落积分",
                        "name": "minClanPoints",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最少部落等级",
                        "name": "minClanLevel",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "游标后",
                        "name": "after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "游标前",
                        "name": "before",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "标签ID列表",
                        "name": "labelIds",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/clans/labels": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "label"
                ],
                "summary": "获取部落标签",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/clans/{tag}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clan"
                ],
                "summary": "获取部落信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "部落标签",
                        "name": "tag",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/clans/{tag}/capital-raid-seasons": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capital"
                ],
                "summary": "获取都城突袭赛季",
                "parameters": [
                    {
                        "type": "string",
                        "description": "部落标签",
                        "name": "tag",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/clans/{tag}/war-log": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "war"
                ],
                "summary": "获取部落战争日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "部落标签",
                        "name": "tag",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "游标后",
                        "name": "after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "游标前",
                        "name": "before",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/gold-pass/current": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utility"
                ],
                "summary": "获取当前 Gold Pass",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/image-search/jobs": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image-search"
                ],
                "summary": "Create image search job",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Base screenshot",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "War target ID",
                        "name": "war_target_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Expected TH",
                        "name": "expected_th",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/image-search/jobs/{job_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image-search"
                ],
                "summary": "Get image search job",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/image-search/jobs/{job_id}/results": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image-search"
                ],
                "summary": "Get image search results",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/image-search/jobs/{job_id}/retry": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image-search"
                ],
                "summary": "Retry image search job",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/layouts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "layouts"
                ],
                "summary": "List base layouts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Town Hall level",
                        "name": "th_level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Layout type",
                        "name": "layout_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Style tag",
                        "name": "style_tag",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Source type",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Review status",
                        "name": "review_status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Quality status",
                        "name": "quality_status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Link status",
                        "name": "link_status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/layouts/{layout_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "layouts"
                ],
                "summary": "Get base layout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Layout ID",
                        "name": "layout_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/layouts/{layout_id}/videos": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "layouts"
                ],
                "summary": "List layout videos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Layout ID",
                        "name": "layout_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "attack_video or defense_replay",
                        "name": "match_group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "exact, similar, or same_th",
                        "name": "match_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/leagues": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "获取联赛列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/leagues/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "获取联赛详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "联赛ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/leagues/{id}/seasons": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "获取联赛赛季列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "联赛ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/leagues/{id}/seasons/{season}/rankings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "获取联赛赛季排名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "联赛ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "赛季ID",
                        "name": "season",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/leagues/{id}/seasons/{season}/tiers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "获取联赛赛季段位列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "联赛ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "赛季ID",
                        "name": "season",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/leagues/{id}/seasons/{season}/tiers/{tier}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "获取联赛赛季段位详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "段位ID",
                        "name": "tier",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/leagues/{id}/seasons/{season}/tiers/{tier}/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "获取玩家联赛赛季历史",
                "parameters": [
                    {
                        "type": "string",
                        "description": "玩家标签",
                        "name": "player_tag",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/locations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ranking"
                ],
                "summary": "获取位置列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/locations/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utility"
                ],
                "summary": "获取位置详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "位置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/locations/{id}/rankings/clans": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ranking"
                ],
                "summary": "获取部落排名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "位置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/locations/{id}/rankings/clans-builder-base": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ranking"
                ],
                "summary": "获取部落夜世界排名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "位置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/locations/{id}/rankings/clans-capital": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ranking"
                ],
                "summary": "获取部落都城排名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "位置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/locations/{id}/rankings/players": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ranking"
                ],
                "summary": "获取玩家排名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "位置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/locations/{id}/rankings/players-builder-base": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ranking"
                ],
                "summary": "获取玩家夜世界排名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "位置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/players/labels": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "label"
                ],
                "summary": "获取玩家标签",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/players/{tag}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "summary": "获取玩家概览",
                "parameters": [
                    {
                        "type": "string",
                        "description": "玩家标签",
                        "name": "tag",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/players/{tag}/battle-log": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "summary": "获取玩家战斗日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "玩家标签",
                        "name": "tag",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/players/{tag}/league-group": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utility"
                ],
                "summary": "获取玩家联赛分组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "玩家标签",
                        "name": "tag",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/players/{tag}/verify-token": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utility"
                ],
                "summary": "验证玩家令牌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "玩家标签",
                        "name": "tag",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "验证请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/utility.VerifyTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/ready": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/war-leagues": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "获取战争联赛列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/war-leagues/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "获取战争联赛详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "联赛ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/war/current": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "war"
                ],
                "summary": "Get current clan war",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Clan tag",
                        "name": "clan_tag",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/war/cwl": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "war"
                ],
                "summary": "Get CWL group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Clan tag",
                        "name": "clan_tag",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/war/cwl/wars/{war_tag}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "war"
                ],
                "summary": "获取 CWL 联赛战争",
                "parameters": [
                    {
                        "type": "string",
                        "description": "战争标签",
                        "name": "war_tag",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/war/snapshots/{war_snapshot_id}/members": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "war"
                ],
                "summary": "List war snapshot members",
                "parameters": [
                    {
                        "type": "string",
                        "description": "War snapshot ID",
                        "name": "war_snapshot_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "clan or opponent",
                        "name": "side",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "utility.VerifyTokenRequest": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "dev",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "WarSpark API",
	Description:      "Reusable Go REST API backend template.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
